---
Name: simple-pdf-preview
---

File:
  extensions:
    - SimplePdfPreviewImageExtension

SimplePdfPreviewImageExtension:
    dependencies:
      generator: %$SimplePdfPreviewImagickGenerator
      folderToSave: "assets/Uploads/"
      imagePrefix: "pdf-preview"

Injector:
  SimplePdfPreviewImagickGenerator:
    class: SimplePdfPreviewImagickGenerator