---
Name: simple-pdf-preview
---

SilverStripe\Assets\File:
  extensions:
    - Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImageExtension

Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImageExtension:
    dependencies:
      generator: '%$Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImagickGenerator'
      folderToSave: "Uploads"
      imagePrefix: "pdf-preview"

Injector:
  Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImagickGenerator:
    class: Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImagickGenerator
