---
Name: simple-pdf-preview
---

SilverStripe\Assets\File:
  extensions:
    - Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImageExtension

Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImageExtension:
    dependencies:
      generator: %$SimplePdfPreviewImagickGenerator
      folderToSave: "Uploads"
      imagePrefix: "pdf-preview"

Injector:
  SimplePdfPreviewImagickGenerator:
    class: Ivoba\SilverStripe\SimplePdfPreview\SimplePdfPreviewImagickGenerator
